### ISSUE TITLE
[advice] About zsh completion script?

### ISSUE THREAD

**Issue by Freed-Wu** [wofr06/lesspipe.sh#101]
I notice <https://github.com/zsh-users/zsh/blob/master/Completion/Unix/Command/_less> also provide a zsh completion script. Why not remove this repository's script to avoid conflict?

And I notice <https://github.com/wofr06/lesspipe/commit/04a123c9ca5fbfb9219f890f546f5c09d7565d2d> format the indent of the script. It is not right, because <https://github.com/zsh-users/zsh/blob/master/Etc/completion-style-guide#L10-L13> use two space not tab to indent zsh completion script.

Thanks.

**Comment by wofr06** [comment]
The `_less` completion script distributed with lesspipe is just an enhanced script, otherwise it does the same as the script distributed with zsh. As the latter is usually part of a package, the integrity of this package would be destroyed when removing the file.
I will change the indentation in the script at a later time according to the style guide. As this is just a cosmetic change, it will not have any influence on the functionality.
Thanks for poiting this out.
