### ISSUE TITLE
Which utility is being used, and select a utility

### ISSUE THREAD

**Issue by indigoviolet** [wofr06/lesspipe.sh#147]
I looked around and didn't find a way for this, please point me in the right direction if I missed it.

1. I would like to know which utility is being run to view a particular file. Maybe something like if LESSVERBOSE is set, print the `cmd` before executing it?

2. It would be great to pick the viewer for different file types. Any way to do that other than uninstalling all conflicting viewers?

**Comment by wofr06** [comment]
To print the `cmd` that gets executed would need code in several places. As `lesspipe.sh` can do several levels of archives there would be more commands to print. The easiest is to run `lesspipe.sh` in verbose mode, i.e. `bash -x lesspipe.sh file` instead of `less file`.

If there are conflicting viewers one could write a `lessfilter` and let it do the job for a particular file type instead of engaging `lesspipe.sh`. Could you give an example what does not work properly?

**Comment by indigoviolet** [comment]
- `bash -x lesspipe.sh` does work; would be nice to document that, or even better turn it on from a flag so that it can be used in the normal `less` flow.

- For instance, if I have `column` and `pandoc` installed, how can I get it to use `pandoc` for CSV? I can write lessfilter, but it just seems like lesspipe already does command selection, so it could support a mechanism like `LESS_CSV_COMMAND=pandoc`. 

Anyway, thank for your work on lesspipe, and this can be closed if you decided not to purse these paths for now.

**Comment by wofr06** [comment]
I could change the preference, trying `pandoc` before `column`, but `pandoc` seems to just recognize commas as separators, not e.g. semicolons. I agree, `column` is inferior, that is why I wrote a new csv viewer [csvtable](https://github.com/wofr06/csvtable). You could give it a try. This is engaged before the other programs.

I added a note on debugging in README.md
