### ISSUE TITLE
piping into less

### ISSUE THREAD

**Issue by anntzer** [wofr06/lesspipe.sh#2]
While skimming the man page of `less` I realized that `LESSOPEN` can handle the case of text being piped into `less`, if `LESSOPEN` is set to `|-cmdname %s`.  In that case the name of the file passed to cmdname is `-`.
It would be nice if lesspipe also handled the case, but right now if `LESSOPEN` is set to `|-lesspipe.sh %s`, `cat $(which lesspipe.sh) | less` results in an empty output.

**Comment by wofr06** [comment]
On Fri, 4 Sep 2015, Antony Lee wrote:

> While skimming the man page of less I realized that LESSOPEN can handle the
> case of text being piped into less, if LESSOPEN is set to |-cmdname %s. In
> that case the name of the file passed to cmdname is -.
> It would be nice if lesspipe also handled the case, but right now if
> LESSOPEN is set to |-lesspipe.sh %s, cat $(which lesspipe.sh) | less results
> in an empty output

This is mostly the result of "optimisations". If the file is pure text 
instead of calling cat I did nothing at all. Then the default behaviour of 
less to display the file unmodified was used.

I will try to avoid these optimisations and by also using the return code 
of the script in conjunction with LESSOPEN empty files could be handled 
properly. Then LESSOPEN has to begin with ||. I will do this change 
probably only in October ...

Wolfgang

**Comment by HaleTom** [comment]
I also vote for being fully compatible with `$LESSOPEN`

When given a filename, `lesspipe` may produce null output but I can work-around with [`ifne -n`](http://linux.die.net/man/1/ifne) (click it).

But working on STDIN, this consumes the input and it is lost forever.

I'm currently using a wrapper to write STDIN to temporary file, but it's ugly and it's slow on large input due to losing the concurrency effect of pipelines.

**Comment by wofr06** [comment]
the latest lesspipe.sh should now produce no output, only if the input would not be modified at all (allowing to watch for growing files). STDIN is always copied unmodified or filtered to STDOUT. lesspipe.sh could however be  easily modified to use cat for unmodified output.
