### ISSUE TITLE
code2color does not work

### ISSUE THREAD

**Issue by savchenko** [wofr06/lesspipe.sh#55]
Using 8267f2f:

```sh
$ code2color test.pl
Scalar found where operator expected at /usr/local/bin/code2color line 3253, near ")$_"
        (Missing operator before $_?)
syntax error at /usr/local/bin/code2color line 3253, near "|^"
  (Might be a runaway multi-line // string starting on line 3249)
syntax error at /usr/local/bin/code2color line 3257, near "}"
Unmatched right curly bracket at /usr/local/bin/code2color line 3260, at end of line
syntax error at /usr/local/bin/code2color line 3260, near "}"
Execution of /usr/local/bin/code2color aborted due to compilation errors.
```

`less -r file` does not result in a coloured output:

![image](https://user-images.githubusercontent.com/300146/117565837-972fd280-b0f2-11eb-8386-d6ac70b33b7c.png)

`pygmentize` works fine despite the incomprehensible colour-scheme:

![image](https://user-images.githubusercontent.com/300146/117565969-410f5f00-b0f3-11eb-95b8-8f2d01646944.png)

**Comment by Konfekt** [comment]
Please try the latest commit.

**Comment by savchenko** [comment]
Still no love:

![image](https://user-images.githubusercontent.com/300146/117897489-17785280-b302-11eb-9581-b89754b9e400.png)

`pygmentize`:

![image](https://user-images.githubusercontent.com/300146/117897515-265f0500-b302-11eb-9370-430f448d4d96.png)

Environment:

```sh
$ env | igrep less
LESSCHARSET=utf-8
LESSQUIET=1
LESS_ADVANCED_PREPROCESSOR=1
LESSOPEN=|lesspipe.sh %s
LESSCOLOR=yes
```

**Comment by Konfekt** [comment]
No more (syntax) errors, but not yet any love (syntax highlighting) that is?

**Comment by savchenko** [comment]
Correct. In addition to the environment details above:
```
Debian 11 "Bullseye"
GNU bash, version 5.1.4(1)-release
perl 5, version 32, subversion 1 (v5.32.1)
```

**Comment by Konfekt** [comment]
Please try the latest commit.

**Comment by savchenko** [comment]
Same. When checked-in from master into a new directory and installed via `./configure --default && make install` there is no highlighting and when applied on top of https://github.com/wofr06/lesspipe/pull/56, I am seeing an error:
```
/usr/local/bin/lesspipe.sh: line 873: syntax error near unexpected token `elif'
/usr/local/bin/lesspipe.sh: line 873: `    elif [[ "$2" = *.log ]] &&'
```
Will need some closer look a bit later.

**Comment by Konfekt** [comment]
I cannot reproduce. Note that all commits where done to the `lesspipe` branch, not `master`. Please try the latest commit.

**Comment by m040601** [comment]
Same thing here.

All color gone in markdown, perl etc

Versions:

- 1.86  color works
- 1.87 color does not work (also borked pdf viewing)
- 1.88 color does not work (pdf viewing is fixed)


Using the Archlinux, official lesspipe packages.
They are built from whatever less pipe releases here, https://github.com/wofr06/lesspipe/releases

https://github.com/wofr06/lesspipe/archive/${pkgver}/lesspipe${pkgver}.tar.gz


> Note that all commits where done to the lesspipe branch, not master

Could  you please clarify, what exactly does one gets from the releases page ?
When you tag a release, and it shows up in , https://github.com/wofr06/lesspipe/releases

Does it contain stuff from "lesspipe" ? "master" ? Whats the policy for making a new release ?

**Comment by Konfekt** [comment]
I can reproduce that markdown is no longer colored, but perl syntax is. Could you point out which one of the five commits between 1.86 and 87 broke perl syntax highlighting? Perhaps d6b434e014227036a2cee0e2567c20f1d8ed1980 ?

**Comment by m040601** [comment]
> Could you point out which one of the .... commits between ...

I cannot point. I dont test and use git versions of lesspipe.

As I tried to explain, I only use official released versions.

So whatever it's there, all the accumulated commits since the previous officially released version A, up to the last officially released version B. That's the only difference that I can test and report.


> but perl syntax is

Sorry, I just  tested again, and need to correct my comment:

Searched for files containing a shebang, ex

`find /usr/ -type f -iname "*.pl"  -exec grep -H  "^\#\!\/usr\/bin" {} \+

Perl:

If the file ends in .pl or .pm and :

- does **not** contain the shebang  `#!/usr/bin/perl` , then it is **not colored.** 
- if it does contain the shebang, it is always colored


Python or Ruby:

If the file ends in .py or .rb  and :

- does **not** contain the shebang  `#!/usr/bin/python` , or #!/usr/bin/ruby , then:
  - if it contains "import", or "class" (python) or "begin", "def" (for ruby) somewhere  it is ** colored.**

- if it does contain the shebang, it is always colored

C:

A file ending  in ".c" is never colored.
A file ending in ".h" is never colored. (needs more testing)


Awk:
A file ending  in ".awk" is only colored if it contains a shebang

**Comment by Konfekt** [comment]
Okay, the detection should also depend on the file extension and not only the shebang. Likely d6b434e caused this. If you comment out those lines again, everything is back to normal?

**Comment by m040601** [comment]
On my current archlinux system, `pacman -Qi lesspipe`

```
Name            : lesspipe
Version         : 1.88-1
Description     : an input filter for the pager less
Architecture    : any
URL             : https://www-zeuthen.desy.de/~friebel/unix/lesspipe.html
....
Packager        : Konstantin Gizdov <arch@kge.pw>
Build Date      : Mon 16 Aug 2021 02:45:05 PM WEST
Install Date    : Tue 24 Aug 2021 09:35:43 PM WEST
```


So I tried `sudo nvim /usr/bin/lesspipe.sh` , and commented out:

```
elif [[ -n "$type" ]]; then
  echo "$type"
  return
```

> everything is back to normal ?

It does seem so. Tested again with .pm, pl, .awk ending files, as well as a lot of Readme.md markdown files. Color seems to be back.

**Comment by m040601** [comment]
By the way, it would also be nice if lesspipe would color yaml files. Ending in .yml or .yaml

Modern colorizers such as the very nice "bat" support yaml.

I see many references in "lesspipe.sh" code to, bat, ccze, mdcat, etc ..
So because "bat" is there, lesspipe  should colorize yaml right out of the box right ? So I thought, But maybe then "code2color" has priority over "bat" , so we dont get color in yaml.


I also see references in "code2color" to pygmentize
And from what I can read in the manual 

>  ... different colorizer can be called within
>        code2color by setting the ENV variable LESSCOLORIZER to the name of an al‐
>        ternative (currently only pygmentize allowed). ...

So I  guess this  "currently only pygmentize allowed)" refers to the python-pygmentize package.
On my system, the package "python-pygmentize" installs a binary callled "pygmentize".

So I tried this and got not color:

` $ less  /usr/share/pandoc/data/translations/es.yaml
`    

But then tried this and got color:

`$ LESSCOLORIZER=pygmentize less  /usr/share/pandoc/data/translations/es.yaml
`

But this "pygmentize" is much slower than "bat". One is written in python, and bat is written in Rust.
Same thing for ccze, very slow pipes.

From all the modern colorizers out there, it seems to me "bat" is the most universal, faster and most polished.  You should really check out "bat --list-languages". It's really impressive. Even logs and git diffs, not only traditional source code get color. And the package "bat" is already distributed and supported officially by many different Linux distributions.

(EDIT: A very nice overview, https://github.com/sharkdp/bat/blob/master/doc/alternatives.md)

I think **bat should have a higher priority in lesspipe**. Or at least also be allowed in "LESSCOLORIZER". And maybe this would also make the work of the lesspipe authors easier, worrying less about maintaining that huge perl monster, code2color.

Let me know if I should open a separate github issue for this "bat" priority question.

I'm trying to study and better grasp  which colorizers lesspipe uses and when.
But I'm not a programmer. Neither am I familiar with the structure of the "lesspipe" and "code2color" files.They are two big for me to understand. But they are like a very old Toyota Corolla, still working and doing their job after all these years.

**Comment by Konfekt** [comment]
Added commits to address both propositions and tagged as 1.89.

**Comment by m040601** [comment]
Thanks for your work, making this tool great !

I dont' want to sound pushy, but I just realized I forgot about json.
It's exactly the same request and treatement I askede for yaml.
Bat also colorizes json.

**Comment by m040601** [comment]
There is  also this "bat" related project called "bat-extras", https://github.com/eth-p/bat-extras/
It's not part of the official "bat", but I'd like to recommend it for reading,
Many usefull ideas and scripting that relate to lesspipe.

> Like lesspipe, batpipe is designed to work with programs that support preprocessing with the LESSOPEN environment variable.

**Comment by Konfekt** [comment]
Oh, yes, sounds like competition. Regarding json, isn't it, like yaml, already  passed to bat as well? That's what's happening here at least.

**Comment by m040601** [comment]
> sounds like competition.

Hhhmm ... kinda of, but not exactly. Maybe bat is the "competition" for "code2color". But is not the competition for lesspipe. Because bat operates (mainly "color" things) on a text file. 

If you feed "bat" with a binary file, it will complain.
It isnt' thought to do other universal things like lesspipe.

It cant do  do the **extremely usefull things** lesspipe does with a pdf, or a mediafile, or a tar.gz archive, etc.

But lesspipe can always piggyback, ride on the "horse" of bat for everything color related, once it has some "text" to present.

**Comment by m040601** [comment]
Another good example of plain text files, that are not "code", but could also benefit from color when viewed with less **are "csv" and "tsv" files**.

Right now,  if you " less somefile.csv" , you only see a normal text file, with no color of course. It's not "source code" for any language.

If it's a big csv with many columns and rows, of different sizes, it's not confortable to view on the terminal. So you open it with Microsoft Excel, or Libreoffice.

Or, if you do want use the terminal, you can use these very usefull text tools, especially thought for tabular data:

- https://visidata.org/
- https://github.com/okbob/pspg
- http://lnav.org/

It's worth spending some time checking them out, because just by the name they use, you sometimes dont realize how they can be used for simple things.

I'm talking about "simple things", that means, I just want to quickly "view" a csv file. I dont want to edit it, resize columns, or do calculations. That's what a simple pager like less is for. 

Now the interesting thing is ,"bat" already does color csv and tsv files.
It cant resize and format the columns  nicely like the other specialized programs of course.
But at least the little color for each column helps a lot viewing the file.

So conclusion.
Lesspipe could also piggyback on "bat" for this case, and open csv and tsv files in less colored" by bat.


Some example of a csv file:

On github

- tabulated, https://github.com/LukeSmithxyz/mutt-wizard/blob/master/share/domains.csv
- "raw", https://raw.githubusercontent.com/LukeSmithxyz/mutt-wizard/master/share/domains.csv

On my terminal, https://imgur.com/a/Wu5T6lh

- viewed with less, no color.
- viewed with bat, nice little colors to help distinguish columns.

**Comment by Konfekt** [comment]
Yes, I agree, but on my machine (that is, using latest version 1.89) everything that lesspipe does not recognize is passed through to bat (it used to be code2color). Thus these requests are only resolved. I think to test them, you would have to wait for the next release though.

**Comment by m040601** [comment]
> you would have to wait for the next release 

Yes. That is correct. I'm still on 1.88. And I'm gonna stay there and wait for my distro to update.

My distro, Archlinux, is "fast". It takes a week maximum to update to the latest released on github lesspipe. Others, Ubuntu, Debian are much much slower.

You cant assume, most non professional programmers using lesspipe, are  using what you just released on github.

**Comment by otandka** [comment]
There's a problem with these [three lines](https://github.com/wofr06/lesspipe/commit/409f2db85803b66206df5bc7ec908be119aab7d6#diff-1d1c7e00b6f9694b32709c3c2f27ce31a59fb99df5ebfd476c5b93206bd3c329L179-L182).  If those lines are commented out, as in 1.89, less is mostly broken on macOS  Catalina 10.15.7.  Basic things like less'ing gz files do not work and show up as binary.  I get lesspipe.sh from brew:

```
Adams src/lesspipe % brew upgrade --dry-run lesspipe
Warning: lesspipe 1.89 already installed
```


I downloaded the GitHub repository and compared tag 1.88 and 1.89:

```
Adams src/lesspipe % git reset 1.88 --hard
HEAD is now at a8a7a33 fix typo
Adams src/lesspipe % ./configure --yes > /dev/null
Adams src/lesspipe % make test |& tail -2
25/12/4 tests passed/ignored/failed in 5 seconds
make: *** [test] Error 4
```

vs

```
Adams src/lesspipe % git reset 1.89 --hard
HEAD is now at b429098 prioritzie bat over code2color
Adams src/lesspipe % ./configure --yes > /dev/null
Adams src/lesspipe % yes | make test |& tail -2
5/15/21 tests passed/ignored/failed in 5 seconds
make: *** [test] Error 21
```

Note also that two failing tests seem to read from stdin, which doesn't happen on 1.88.

**Comment by Konfekt** [comment]
To summarize:

[Here](https://github.com/wofr06/lesspipe/issues/55#issuecomment-905410262) @m040601 informed us that

> So I tried sudo nvim /usr/bin/lesspipe.sh , and commented out:
>
>elif [[ -n "$type" ]]; then
>  echo "$type"
>  return
>
>  everything is back to normal ? It does seem so. 

and [here](https://github.com/wofr06/lesspipe/issues/55#issuecomment-932800055) informs us that 

> If those lines are commented out, as in 1.89, less is mostly broken on macOS Catalina 10.15.7.

@wofr06 could perhaps reconcile these diverging opinons? Maybe a check for Macos is needed?

**Comment by otandka** [comment]
I ran make test on a Debian 10 (buster) system to compare 1.88 and 1.89.  Here also 1.89 is badly broken 25 tests fail to pass.  So it isn't just a MacOS issue.
```
5/11/25 tests passed/ignored/failed in 18 seconds
make: *** [Makefile:10: test] Error 25
% git log --oneline -n 1
b429098 (HEAD -> lesspipe, tag: 1.89) prioritzie bat over code2color
```

On the other hand 1.88 passes all (configured) tests:
```
ota@alfriston:tmp/lesspipe% git reset 1.88 --hard
HEAD is now at a8a7a33 fix typo
ota@alfriston:tmp/lesspipe% ./configure --yes >/dev/null
% echo $?
0
% make test |& tail -2
less    testok/test.tar.zst                              ok
32/9/0 tests passed/ignored/failed in 2 seconds
```

**Comment by Konfekt** [comment]
As far as I recall @wofr06 introduced the three lines in question to make these tests pass, alas, this issue arose. Perhaps postponing passing the output of `$type` before `$mime` is a good compromise?

**Comment by m040601** [comment]
>  Basic things like less'ing gz files do not work and show up as binary. 


I can confirm this also happens, in Archlinux, v1.89.
Same thing happens with for zstd "z" compressed files.

All of these files open perfectly using

gzip /usr/bin/zcat
gzip /usr/bin/zgrep
gzip /usr/bin/zless

or

zstd /usr/bin/zstdcat
zstd /usr/bin/zstdgrep
zstd /usr/bin/zstdless

**Comment by Konfekt** [comment]
Did the [last commit](https://github.com/wofr06/lesspipe/commit/42176ff4e369d4dd78dec638e46dca602857d36d) change this?

**Comment by m040601** [comment]
as of 20.October.2021:

 $ file  /usr/share/man/man1/bash.1.gz 


`/usr/share/man/man1/bash.1.gz: gzip compressed data, max compression, from Unix, original size modulo 2^32 336009`




   $ file /usr/share/info/bash.info.gz 

`/usr/share/info/bash.info.gz: gzip compressed data, max compression, from Unix, original size modulo 2^32 540756`



   $ less /usr/share/info/bash.info.gz 

`"/usr/share/info/bash.info.gz" may be a binary file.  See it anyway? `


   $ pacman -Qi  lesspipe


```
Name            : lesspipe
Version         : 1.89-1
Build Date      : Thu 02 Sep 2021 09:32:18 AM WEST
Install Date    : Thu 02 Sep 2021 10:56:51 AM WEST

```


  $ echo $LESS

`-Ri --use-color -Dd+r$Du+b`

  $ echo $LESSOPEN 

`|/usr/bin/lesspipe.sh %s`




> Did the last commit change this?

As I said before, I dont use "git" or "specific commit" versions. I only use whatever lesspipe releases, here, https://github.com/wofr06/lesspipe/releases. In this case, that is version 1.89


I did however try to temporarly test that specific commit. I briefly edited /usr/bin/lesspipe.sh and substituted:

`if [[ -n "$mime" ]]; then`

for:

```
if [[ -n "$type" ]]; then
  return="$type"
elif [[ -n "$mime" ]]; then
```

Same thing happers:

`"/usr/share/info/bash.info.gz" may be a binary file.  See it anyway? `

**Comment by Konfekt** [comment]
Thank you. To understand what changed in [filetype()](https://github.com/wofr06/lesspipe/blob/42176ff4e369d4dd78dec638e46dca602857d36d/lesspipe.sh#L120) could you also provide the output of [file -i](https://github.com/wofr06/lesspipe/blob/42176ff4e369d4dd78dec638e46dca602857d36d/lesspipe.sh#L181) ?

**Comment by m040601** [comment]
$ file -i /usr/share/man/man1/bash.1.gz

/usr/share/man/man1/bash.1.gz: application/gzip; charset=binary


    $ pacman -Qi  file

Name            : file
Version         : 5.41-1
Description     : File type identification utility
Architecture    : x86_64
URL             : https://www.darwinsys.com/file/
Groups          : base-devel
Provides        : libmagic.so=1-64
Depends On      : glibc  zlib  xz  bzip2  libseccomp  libseccomp.so=2-64
Optional Deps   : None
Required By     : checksec  ext4magic  mpd-notification  nano  sox  util-linux
                  xdg-utils  zathura  zim-tools



    $ mimetype -a /usr/share/man/man1/bash.1.gz

/usr/share/man/man1/bash.1.gz: application/gzip
/usr/share/man/man1/bash.1.gz: application/gzip
/usr/share/man/man1/bash.1.gz: application/octet-stream

    $ type mimetype

mimetype is hashed (/usr/bin/vendor_perl/mimetype)

    $ pacman -Qo mimetype
/usr/bin/vendor_perl/mimetype is owned by perl-file-mimeinfo 0.30-2



    $ pacman -Qi  perl-file-mimeinfo

Name            : perl-file-mimeinfo
Version         : 0.30-2
Description     : Determine file type, includes mimeopen and mimetype
URL             : https://metacpan.org/release/File-MimeInfo
Depends On      : perl-encode-locale  perl-file-basedir  perl-file-desktopentry
                  shared-mime-info
Optional Deps   : None
Required By     : None
Optional For    : xdg-utils

**Comment by m040601** [comment]
$ cat > textfile.txt

hello world

    $ file textfile.txt

textfile.txt: ASCII text

    $ file -i textfile.txt

textfile.txt: text/plain; charset=us-ascii

    $ gzip textfile.txt

...


    $ file textfile.txt.gz

textfile.txt.gz: gzip compressed data, was "textfile.txt", last modified: Thu Oct 21 01:05:13 2021, from Unix, truncated

    $ file -i textfile.txt.gz

textfile.txt.gz: application/gzip; charset=binary

    $ less textfile.txt.gz

"textfile.txt.gz" may be a binary file.  See it anyway?

**Comment by m040601** [comment]
Just a quick update to report that this issues with color and compressed single files or archives seem to be solved.

A big thank you to anyone involved.

As of today  on my system with the latest updates and the latest version of lesspipe:

Arch Linux

```

  Name            : lesspipe
  Version         : 1.91-1
  URL             : https://www-zeuthen.desy.de/~friebel/unix/lesspipe.html
  Licenses        : GPL
  Depends On      : less  perl
  Optional Deps   : rpmextract: support for rpm files
                    fastjar: support for jar files [installed]
                    unzip: support for zip files [installed]
                    unrar: support for rar files [installed]
                    p7zip: support for 7za files [installed]
                    cabextract: support for cab files
                    cdrtools: support for iso files [installed]
                    html2text: support for html files
                    ghostscript: support for ps files [installed]
                    djvulibre: support for DjVu files [installed]
                    odt2txt: support for OpenDocument files [installed]
                    antiword: support for word file [installed]
                    catdoc: support for word file [installed]
                    pandoc: support for word file [installed]
                    libreoffice-fresh: support for MS Office files
                    unrtf: support for rtf file [installed]
                    mediainfo: support for mp4 file [installed]
                    imagemagick: support for some image file [installed]
  Optional For    : source-highlight
  Packager        : Konstantin Gizdov <arch@kge.pw>
  Build Date      : Wed 10 Nov 2021 07:56:19 PM WET
  Install Date    : Wed 10 Nov 2021 08:26:59 PM WET
  Install Reason  : Explicitly installed

```


Viewing single compressed files  (.gz, .xz, .zst etc) seems to work fine now. In archives,  it even colors files inside tar.gz and  tar.zst archives. (cant' remember if it did that before)
