### ISSUE TITLE
Syntax error in code2color

### ISSUE THREAD

**Issue by taerath** [wofr06/lesspipe.sh#7]
I'm getting the following error with a freshly downloaded tarball (and after running `configure`):

```
$ less diff
Array found where operator expected at /usr/local/bin/code2color line 3260, near "} "
        (Missing operator before  ?)
syntax error at /usr/local/bin/code2color line 3260, near "} @ARGV"
Execution of /usr/local/bin/code2color aborted due to compilation errors.
```

**Comment by taerath** [comment]
```
$ perl --version

This is perl 5, version 20, subversion 2 (v5.20.2) built for x86_64-linux-gnu-thread-multi
(with 45 registered patches, see perl -V for more detail)
```

**Comment by wofr06** [comment]
On Fri, 29 Jan 2016, taerath wrote:

> I'm getting the following error with a freshly downloaded tarball (and after
> running configure):
> 
> $ less diff
> Array found where operator expected at /usr/local/bin/code2color line 3260, 
> near "} "
>         (Missing operator before  ?)
> syntax error at /usr/local/bin/code2color line 3260, near "} @ARGV"
> Execution of /usr/local/bin/code2color aborted due to compilation errors

The words "freshly downloaded tarball" gave me the hint, where this wrong 
version still could lay around. I found it on the desy.de website and have 
replaced the tarball with the corrected version. The versions on 
sourceforge and on github were up to date and did not contain the typo.

The fix is just to replace the contents of line 3260:

@ARGV = grep {$_ ne '-'} @ARGV;

This is also on github:

https://github.com/wofr06/lesspipe/commit/05748269d165628b3d40644de144060e9a6971b8

## Thaks for reporting the bug

Best regards
Wolfgang Friebel
