### ISSUE TITLE
Possible to use LESSCOLORIZER for Markdown files?

### ISSUE THREAD

**Issue by mathomp4** [wofr06/lesspipe.sh#84]
A query sort of based on #83, I think I finally figured things as to why I wasn't seeing the color I thought. It's because I have `pandoc` installed and I was hitting this:

https://github.com/wofr06/lesspipe/blob/323eb6b4da766a44cecdec8c3335de989bce918e/lesspipe.sh#L454-L457

However, I really like using `bat` to read my Markdown files (I'd love to use `mdcat` but it freaks out with some of my files). But I also like having `pandoc` around.

So I was wondering, is there a way to get lesspipe to use `bat` as my Markdown colorizer but still keep `pandoc` in my path?

**Comment by wofr06** [comment]
obviously there are several programs around called mdcat. I am using the one from https://github.com/lunaryorn/mdcat
(actually 0.24, but 0.26 is released). I had no issues up to now using it. It would be interesting to see a file where this version of mdcat doesn't work.

If you dislike calling mdcat you could simply comment out the line containing mdcat in the markdown clause (line 456), then it is still called for pptx files. Alternatively you could replace all occurrences of 'has_cmd mdcat' by 'has_cmd mdcat_not'.

Then pandoc is used. Both with pandoc and bat I do not see colors for markdown files. So I don't know why you want bat instead of pandoc.

If you do not want to touch lesspipe.sh you could write a small script lessfilter (or .lessfilter) where you handle markdown files (they are recognized by the file extension only). As a simplistic example the following code should work:

#!/usr/bin/env bash

if [[ "$1" = *.md ]]; then
 # call your favorite markdown program here, e.g. bat $1
  exit 0;
fi
exit 1;
